### ISSUE TITLE
Add excluding files feature to the rules

### ISSUE THREAD

**Issue by dev-yakuza** [sider/goodcheck#119]
I can exclude the files for all rules in the following document.

[https://sider.github.io/goodcheck/docs/configuration#excluding-files](https://sider.github.io/goodcheck/docs/configuration#excluding-files)

But I can not exclude the files for a rule. Is it possible to exclude files for one rule?
For example,

```
- id: only.png.not.jpg
    pattern:
      - .jpg
      - .jpeg
    glob:
      - "**/ja.html"
    exclude:
      - privacy.html
      - security.html
    message: |
      Stop to use jpg format
```

Thanks

**Comment by ybiquitous** [comment]
`exclude` should be on the top level like this:

```yaml
rules:
  - id: only.png.not.jpg
    pattern:
      - .jpg
      - .jpeg
    glob:
      - "**/ja.html"
    message: |
      Stop to use jpg format

exclude:
  - privacy.html
  - security.html
```

**Comment by dev-yakuza** [comment]
If I set `exclude` on the top level, the file is excluded for all rules, but I want to exclude the file only for one rule.

```yaml
rules:
  - id: only.png.not.jpg
    pattern:
      - .jpg
      - .jpeg
    glob:
      - "**/ja.html"
    exclude:
      - privacy.html
      - security.html
    message: |
      Stop to use jpg format

exclude:
  - Gemfile.lock
  - package-lock.json
```

is it not necessary? 🤔
