### ISSUE TITLE
`goodcheck check` succeed when unknown rule is given

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#125]
When the following `goodcheck.yml` is given,

```yaml
# goodcheck.yml
rules:
  - id: foo
    pattern: foo
    message: Disallow `foo`
```

the following command succeeds unexpectedly:

```console
$ goodcheck check --rule=unknown && echo "Pass"
Pass
```

I think the expected behavior is like this:

```console
$ goodcheck check --rule=unknown
Unknown rule "unknown"

#=> exit with non-zero code
```
