### ISSUE TITLE
Add rule location in JSON output

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#127]
## Example

`goodcheck.yml`:

```yaml
rules:
  - id: disallow-standard-error
    pattern:
      - token: StandardError
    glob: lib/**/*.rb
    message: Disallow `StandardError`.
    justification:
      - When there is an unavoidable reason to use `StandardError`.
```

`goodcheck check --format json lib/`:

```json5
[
  {
    "rule_id": "disallow-standard-error",
    "path": "lib/errors.rb",
    "location": {
      "start_line": 2,
      "start_column": 16,
      "end_line": 2,
      "end_column": 29
    },
    "message": "Disallow `StandardError`.",
    "justifications": [
      "When there is an unavoidable reason to use `StandardError`."
    ],
    "rule_location": { //<= new property
      "uri": "file:///tmp/project/goodcheck.yml", // or https://some.host/shared/rules.yml
      "line": 2
    }
  }
]
```
