### ISSUE TITLE
Add rule level (severity)

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#129]
I think it useful that a rule has a level of importance (*severity*). For example:

```yaml
# goodcheck.yml
rules:
  - id: disallow_foo
    pattern: foo
    message: Disallow `foo`
    level: error
  - id: warn_bar
    pattern: bar
    message: Warn `bar`
    level: warning

level:
  - error
  - warning
  - ...
```

Suggestions:

- Add `level` (*string*) to a rule
- Add top-level `level` (array of *string*) for allow-list of levels
- If the top-level `level` is omitted,
  - the default level list is used, e.g. `[error, warning, info]`
  - or the level check is not performed (any levels are allowed)

Please feedback!
