### ISSUE TITLE
Support autofix

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#173]
I think it very useful to provide a feature that users can automatically fix the detected file.

For example, given `goodcheck.yml`:

```yaml
rules:
  - id: disallow-foo
    pattern: foo
    message: Disallow `foo`. Use `bar` instead.
    fix: bar
```

Run `goodcheck fix` (or `goodcheck check --fix`, which is better?):

```console
$ goodcheck check
test.txt:1:1: Disallow `foo`
foo
^~~

$ goodcheck fix
test.txt fixed!

$ cat test.txt
bar
```

I want more suggestions, questions, or help. 🙏
