### ISSUE TITLE
Request: Arrays for patterns

### ISSUE THREAD

**Issue by gfx** [sider/goodcheck#41]
There are cases that I'd like to use arrays of token/literal/regexp for simplicity.

For example:

```yaml
  - id: bitjourney.do-not-use-obsolete-names
    pattern:
      token:
        - obsolete_name
        - obsolete_names
        - another_obsolete_name
        - another_obsolete_names
```

**Comment by ybiquitous** [comment]
I recommend as follow:

```yaml
pattern:
  - token: obsolete_name
  - token: obsolete_names
  - token: another_obsolete_name
  - token: another_obsolete_names
```

If you may feel a bit verbose, but I think the above example is clear.

Also, I'm concerned that the learning cost of `goodcheck.yml` might increase if we would support this shortcut format.
