### ISSUE TITLE
Request: Allow new `pass:` and `fail:` combinations

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#48]
When there is so many `pass:` and `fail:`, it is harder to find the relationships between `pass:` and `fail:`.
As the following example, if it would be able to write the corresponding `pass:` and `fail:` at the near position, I think the YAML configuration would be more readable.

Note: This feature is inspired by [Querly](https://github.com/soutaro/querly/blob/55b2a6dd71c03d2e9a3268a203ef526d9dfaf4ef/template.yml#L18-L26).

```yaml
# Current
pass:
  - Good 1...
  - Good 2...
  - Good 3...
  # other good examples...
fail:
  - Bad 1...
  - Bad 2...
  - Bad 3...
  # other bad examples...

# New
examples:
  - pass: Good 1...
    fail: Bad 1...
  - pass: Good 2...
    fail: Bad 2...
  - pass: Good 3...
    fail: Bad 3...
  # other good & bad combinations...
```
