### ISSUE TITLE
andで検知を行う機能が欲しい

### ISSUE THREAD

**Issue by tinagaki** [sider/goodcheck#67]
こんにちは
機能要望としてISSUEを書かせていただきたいと思っています。

### 機能要望
html,XMLのようなものgoodcheckを行いたいさいに機能が足りなく
下記機能を一考していただければと思っています。
- パターン検知したあとにandでさらに検知を行う機能をつけてほしい

### 経緯
AndroidManifest.xml のactivityタグのexportを必ず明示的に書くようにしたい。
Manifest内に

```
<?xml version="1.0" encoding="utf-8"?>
<manifest  ....>
  
        <activity android:name="com.HUGAHUGA.LoginActivity"> ← fail

        <activity android:name="com.HOGEHOGE.LoginActivity"
                  android:exported="false"/> ← pass
```
上記のようなようなものを対応できるようにしたいと思った際に
1. はじめにactivityタグを複数行で検知を行い 
1. 検知したものの中からnot構文の正規表現でexportがないものを探す
ということが必要かと思います。

html.xmlだと似たタグを使う場合があり、ある属性がない場合にのみ除外したいという要望が他にもあるかと考えました
一度一考をお願いしたいです。

**Comment by soutaro** [comment]
ご要望ありがとうございます。ユースケースとして理解はできますし、ぜひ提供したい機能ではあるのですが、どのように実装するかが難しくて、手が動かせていません。今後とも検討していきますので、しばらく考える時間をいただければと。

ちなみに、例に挙げてくださった `android:exported` に関して言えば、Ruby 2.4で導入された非包含演算子 `(?~...)` を使ってパターンの定義が可能のようです。

```
rules:
  - id: export
    pattern:
      - regexp: "<activity(?~android:exported)>"
        multiline: true
    message:
      Should write `android:exported` explicitly
    fail:
      - |
        <activity android:name="com.HUGAHUGA.LoginActivity">
    pass:
      - |
        <activity android:name="com.HOGEHOGE.LoginActivity"
                  android:exported="false"/>
      - |
        <div>hello world</div>
```

**Comment by tinagaki** [comment]
返信および機能検討ありがとうございます。
動作も確認できました。
一旦自分の要望としては検知してほしい部分ができるのでこちらはクローズでもよいかもしれません。

追加でついでに、こちらで動作確認をしていた際に不明だった部分を確認させてください。
上記のような設定で

```
<activity android:name="com.HUGAHUGA.LoginActivity">
<activity android:name="com.HUGAHUGA.LogoutActivity">

```
のようなXMLだった場合に２点指摘をしてほしいのですが手元では確認できませんでした。

multiline: true
の影響なのかなとおもっているのですがこちらは検知が可能でしょうか？
別ISSUEのほうがよければ別ISSUEを立てようと思います。
よろしくお願いいたします。

**Comment by ybiquitous** [comment]
@tinagaki 返信が遅くなりまして、大変申し訳ありません 🙇 

["Regular Expressions Cookbook"](https://books.google.co.jp/books?id=0Msuh5Vq-uYC&pg=PA550) という書籍に載ってある方法が、参考になるかと思います。

```
<activity\b(?![^>]*?\sandroid:exported\b)([^>]*)>
```

例えば、こちらが一例になります。

```yaml
# An example of goodcheck.yml
rules:
  - id: export
    pattern:
      - regexp: >-
          <activity\b(?![^>]*?\sandroid:exported\b)([^>]*)>
        multiline: true
    message: |
      Should write `android:exported` explicitly
    fail:
      - |
        <activity android:name="com.HUGAHUGA.LoginActivity"></activity>
      - |
        <activity android:name="com.HUGAHUGA.LoginActivity">
        </activity>
      - |
        <activity android:name="com.HUGAHUGA.LoginActivity"/>
    pass:
      - |
        <activity android:name="com.HOGEHOGE.LoginActivity" android:exported="false">
        </activity>
      - |
        <activity android:name="com.HOGEHOGE.LoginActivity" android:exported="false"/>
      - |
        <activity android:name="com.HOGEHOGE.LoginActivity"
                  android:exported="false"/>
      - |
        <div>hello world</div>
```

こちらで解決可能と思いますので、一旦クローズとさせていただきます。問題があるようでしたら、リオープンお願いします。
