### ISSUE TITLE
`glob` does not work for dot files

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#84]
For example:

https://sider.review/gh/repos/156170852/pulls/36

https://github.com/sider/goodcheck-rules/blob/91adde13a884398852465049b7b1a0b73a96a48b/rules/ruby.yml#L1-L4

```yaml
- id: review.sider.ruby.dot-ruby-version
  glob: .ruby-version
  message: Consider if need to update also the Ruby version in `Dockerfile` or `.circleci/config.yml` etc.
  justification: When no other files writing the Ruby version
```
