### ISSUE TITLE
pattern: /foo/ で設定するとundefined method `multiline?'が発生

### ISSUE THREAD

**Issue by issei126** [sider/goodcheck#96]
設定ファイルを以下のように書いています

```
rules:
  - id: io.carely.take_stresscheck
    pattern: /受験/
    message: 受検ではないですか？
    glob:
      - app/views/**/*.html.slim
      - config/locales/**/*.yaml
      - public/**/*.html
```

この設定で実行すると

```
bundle exec goodcheck test
#<NoMethodError: undefined method `multiline?' for /受験/:Regexp>
  /bundle/gems/goodcheck-2.4.0/lib/goodcheck/config_loader.rb:363:in `load_pattern'
  /bundle/gems/goodcheck-2.4.0/lib/goodcheck/config_loader.rb:298:in `block in retrieve_triggers'
```

と表示されます。

該当箇所は https://github.com/sider/goodcheck/blob/master/lib/goodcheck/config_loader.rb#L363
となっており、
https://docs.ruby-lang.org/ja/latest/class/Regexp.html をみても `multiline?` というメソッドはないようです。

こちら実装あっているでしょうか？

当方
Ruby: 2.4.1
goodcheck: 2.4.0
となっております。
このバージョンのドキュメントをみても `multiline?` というメソッドはないようです。
https://docs.ruby-lang.org/ja/2.4.0/class/Regexp.html

よろしくおねがいします
